AWSTemplateFormatVersion: 2010-09-09
Description: 3 tier production grade application infra

Parameters:
    ProjectPartialsS3BucketName:
        Type: String

Resources:
  NetWorkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
        Description: "production grade multi tier application"
        TemplateURL: !Sub "https://s3.amazonaws.com/${ProjectPartialsS3BucketName}/network.yml"