AWSTemplateFormatVersion: 2010-09-09
Description: 3 tier production grade application infra

Resources:
  WebInfraS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pdw-s3-bucket-sandbox-ui-infra
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false


  WebInfraS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebInfraS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicAccessForWebsite
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${WebInfraS3Bucket.Arn}/*"

Outputs:
  WebURL:
    Value: !GetAtt WebInfraS3Bucket.WebsiteURL
    Export:
      Name: "pdw-WebInfraS3Bucket:WebsiteUrl"